# Generated by Django 5.2 on 2025-04-12 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_product_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('clothing', 'Clothing'), ('electronics', 'Electronics'), ('accessories', 'Accessories'), ('footwear', 'Footwear'), ('watches', 'Watches'), ('bags', 'Bags'), ('other', 'Other')], default='other', max_length=64),
        ),
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL),
        ),
    ]
