# Generated by Django 5.2 on 2025-04-12 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_product_type_alter_product_seller'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='type',
            new_name='category',
        ),
    ]
