# Generated by Django 5.2 on 2025-04-11 01:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_customuser_is_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterSeller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=64)),
                ('province', models.CharField(max_length=64)),
                ('postal_code', models.CharField(max_length=64)),
                ('business_description', models.TextField()),
                ('primary_product_category', models.CharField(choices=[('clothing', 'Clothing'), ('electronics', 'Electronics'), ('home_appliances', 'Home Appliances'), ('books', 'Books'), ('other', 'Other')], default='clothing', max_length=64)),
                ('document', models.FileField(upload_to='')),
                ('verified', models.BooleanField()),
                ('registered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
