# Generated by Django 5.2 on 2025-04-11 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_registerseller'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_no',
            field=models.IntegerField(default=98),
        ),
        migrations.AlterField(
            model_name='registerseller',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
