# Generated by Django 5.2 on 2025-04-11 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_customuser_phone_no_alter_registerseller_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
