# Generated by Django 5.2 on 2025-04-12 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_product_main_image_alter_productimages_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='key_features',
            field=models.TextField(blank=True, null=True),
        ),
    ]
