# Generated by Django 5.2 on 2025-04-12 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_product_key_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='key_features',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(upload_to='product_images/'),
        ),
    ]
