# Generated by Django 5.2 on 2025-06-12 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_rename_phone_customuser_phone_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiniOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mini_orders', to='dashboard.product')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.FloatField()),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('delivery_status', models.CharField(default='Pending', max_length=64)),
                ('shipping_address', models.CharField(max_length=256)),
                ('shipping_city', models.CharField(max_length=64)),
                ('shipping_province', models.CharField(max_length=64)),
                ('tracking_number', models.CharField(blank=True, max_length=64, null=True)),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('payment_status', models.CharField(default='Pending', max_length=64)),
                ('payment_method', models.CharField(default='Cash on Delivery', max_length=64)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('products', models.ManyToManyField(related_name='orders', through='dashboard.MiniOrder', to='dashboard.product')),
            ],
        ),
        migrations.AddField(
            model_name='miniorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mini_orders', to='dashboard.order'),
        ),
    ]
