# Generated by Django 5.2 on 2025-06-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_miniorder_order_miniorder_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='miniorder',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
