# Generated by Django 5.2 on 2025-06-12 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='delivery_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='seller',
        ),
    ]
