# Generated by Django 5.2 on 2025-10-13 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_transactiondetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondetails',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='dashboard.order'),
        ),
        migrations.AlterField(
            model_name='transactiondetails',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='dashboard.product'),
        ),
    ]
