# Generated by Django 5.1.3 on 2025-10-15 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_alter_transactiondetails_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerseller',
            name='primary_product_category',
            field=models.CharField(choices=[('clothing', 'Clothing'), ('electronics', 'Electronics'), ('footwear', 'Footwear'), ('home_appliances', 'Home Appliances'), ('books', 'Books'), ('other', 'Other')], default='clothing', max_length=64),
        ),
    ]
